name: Deploy Project

# Event trigger for the workflow
on:
  push:
    branches:
      - main  # The workflow triggers on push to the 'main' branch

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust this if you're using a different version
        
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          publish_branch: gh-pages

  deploy-admin:
    name: Deploy Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust this if you're using a different version
        
      - name: Install dependencies
        run: |
          cd admin
          npm install

      - name: Build admin
        run: |
          cd admin
          npm run build
